### ISSUE TITLE
Add script for tracking info from new contributors

### ISSUE THREAD

**Issue by thisisnic** [thisisnic/arrowdash#2]
Tracking issues from new contributors, track one-timers, help track newer folks who might need help with things or to become committers (count PRs and other signs of engagement) - could flag it up on the dashboard

**Comment by thisisnic** [comment]
CC @alenkafrim

**Comment by AlenkaF** [comment]
Closing this issue as it is done with https://github.com/thisisnic/arrowdash/pull/6 and am testing if I have permissions to do it =)
